services:
  - type: web
    name: gemini-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
